# Generated by Django 4.2.7 on 2024-02-08 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0008_rename_distrbutor_distributor'),
        ('distributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributor',
            name='distributors',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ss.distributor'),
        ),
    ]
