# Generated by Django 4.2.7 on 2024-02-08 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0002_distributor_distributors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='distributor',
            old_name='distributors',
            new_name='distributor',
        ),
    ]
