# Generated by Django 4.2.7 on 2024-02-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0003_rename_distributors_distributor_distributor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
