# Generated by Django 4.2.7 on 2024-02-08 09:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distributor', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distributor',
            new_name='Distributors',
        ),
    ]
