# Generated by Django 4.2.7 on 2024-02-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0006_rename_distributor_distributors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributors',
            name='address',
        ),
        migrations.RemoveField(
            model_name='distributors',
            name='phonenumber',
        ),
        migrations.RemoveField(
            model_name='distributors',
            name='user',
        ),
        migrations.AddField(
            model_name='distributors',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='distributors',
            name='password',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='distributors',
            name='username',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
