# Generated by Django 4.2.7 on 2024-02-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0007_remove_distributors_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributors',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
