# Generated by Django 4.2.7 on 2024-02-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0008_alter_distributors_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distributors',
            new_name='Admin',
        ),
    ]
