# Generated by Django 4.2.7 on 2024-07-02 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distributor', '0010_requirements'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='distributor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='distributor.admin'),
        ),
    ]
