# Generated by Django 4.2.7 on 2024-02-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0003_stockist_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='stockist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='stockist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='stockist',
            name='username',
        ),
    ]
