# Generated by Django 4.2.7 on 2024-02-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0005_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='items',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
