# Generated by Django 4.2.7 on 2024-02-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0006_items_is_available_items_is_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrbutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.TextField()),
                ('phonenumber', models.IntegerField()),
            ],
        ),
    ]
