# Generated by Django 4.2.7 on 2024-02-07 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ss', '0007_distrbutor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Distrbutor',
            new_name='Distributor',
        ),
    ]
